name: Build and Deploy Strimzi images (change-api-group)

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/deploy.yaml
    with:
      repo: lburgazzoli/strimzi-kafka-operator
      branch: change-api-group
    secrets:
      continer-registry: ${{ env.CONTAINER_REGISTRY }}
      continer-registry-organization: ${{ env.CONTAINER_REGISTRY_ORGANIZATION }}
      continer-registry-username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
      continer-registry-password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
      github-token: "${{ secrets.GITHUB_TOKEN }}"