name: Build and Deploy Camel K Dev images (main)

on:
  #schedule:
  #  - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/deploy.yaml
    with:
      repo: lburgazzoli/strimzi-kafka-operator
      branch: change-api-group
    secrets:
      quay-username: ${{ secrets.QUAY_USERNAME }}
      quay-token: ${{ secrets.QUAY_ROBOT_TOKEN }}
      quay-repo: ${{ secrets.QUAY_REPO }}
      quay-org: ${{ secrets.QUAY_ORG }}