name: Build and Deploy Strimzi images (change-api-group)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/deploy.yaml
    with:
      repo: lburgazzoli/strimzi-kafka-operator
      branch: change-api-group
    secrets:
      continer-registry-username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
      continer-registry-password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}